README.md
appveyor.bat
appveyor.yml

Racket 6.4 was released about 2 months ago, and the default version in the [download page](https://download.racket-lang.org/) is already 6.4.
I think it's better to update Racket to 6.4.

Update Racket to 6.4

---

appveyor.yml
scripts/update-repo.sh

This change will make links for official patches. A simple example can be seen [here](https://github.com/chrisbra/vim-win32-installer/releases/tag/v7.4.1752)
Also, using `set /p=<file` seems to be restricted to a some bytes (around 1K or so) so output will be truncated if there is a long changelog. Therefore, use the `for /f....` approach which seems to work okay.

Make Patch URLs Links to actual tag from vim repository

---

appveyor.bat
appveyor.yml

As requested on vim_use, create two new archives `gvim_*_pdb.zip` that contain only the pdb files for better debugging of the windows binaries.
An example can be seen [here](https://github.com/chrisbra/vim-win32-installer/releases/tag/v7.4.1832)

Create new archives for the pdb files

---

appveyor.bat
if_ver.vim

This enables to show version numbers of all if_xx (mainly for debugging).
Also fixes that $PATH was not set properly when running the tests.
Here is an example output:
https://ci.appveyor.com/project/k-takata/vim-win32-installer/build/33/job/tqbewjwh8ys2dl0a#L746

Show all interface versions

---

appveyor.bat

Now AppVeyor has preinstalled NSIS 2.50.  We don't need to install it by ourself.

Use preinstalled NSIS

---

appveyor.bat
appveyor.yml

This keeps downloaded files in a cache unless appveyor.bat is changed.
If appveyor.bat is updated the cache should be discarded because the
downloaded files might be outdated.
See: http://www.appveyor.com/docs/build-cache

Use build cache for downloaded files

---

README.md
appveyor.bat
patch/README.md

This allows to build Vim with additional patches. Place your experimental patch into the patch directory with the extension .patch. All files in that directory will then be applied in an alphanumeric order (?)

Apply patches before building

---

README.md
appveyor.bat
appveyor.yml

Perl 5.24 was released, so compile against 5.24
Example build script: https://ci.appveyor.com/project/chrisbra/vim-win32-installer-33v6e/build/53/job/357ohnhh85ie62f5

Update Perl to 5.24

---

appveyor.bat
appveyor.yml

The bigvim(64).bat is updated to use Python 3.5 by 7.4.2302. This commit follows it.
Note that python35.dll is not installed in `C:\Windows\System`, which differs from Python 3.4. We need to add `C:\python35(-x64)` to the %PATH%.

Update Python3 to 3.5

---

appveyor.bat

Appveyor seems to have switched to python 2.7.12
so the workaround about changing the registry keys for python should not
be needed anymore.
CC @k-takata for comment

Workaround for python 2.7.12 not needed anymore

---

appveyor.bat

ActivePerl changed their links. The old Perl link isn't even available anymore for downloads. So let's try with a newer release 5.24.1 ping @k-takata for review

Update Perl installation

---

appveyor.bat

Update gettext to latest release from https://github.com/mlocati/gettext-iconv-windows/releases/
Note: I am not hundert percent sure, that localizing works correctly. I would appreciate a test.
Currently fails, because of the changed perl download URLs. Sample builds can be downloaded from [here](https://github.com/mlocati/gettext-iconv-windows/issues/6#issuecomment-278348574) (I accidently deleted those builds from my chrisbra/vim-win32-installer fork, sorry for that)

update gettext version

---

README.md
appveyor.bat
appveyor.yml

* ActiveTcl
x64: 8.6.6.8606
x86: 8.6.6.8607
The installer is now MSI exe. The command line options are changed.
* The compiler is updated to VC2015, because ActiveTcl 8.6.6 is built by
VC2015.
* Ruby is updated to 2.4, because Ruby 2.3 or earlier cannot be built by
VC2015.
* VC2010 is still used for building gvimext.dll, because it is easier to
build for targeting Windows XP.

Update Tcl to 8.6.6, Ruby to 2.4

---

appveyor.bat
patch/nsis-install-winpty.patch

Include winpty.dll and winpty-agent.exe in the installer and zip packages.
This PR includes `patch/nsis-install-winpty.patch` temporary. This should be removed when this is included in the official repository.

Include winpty

---

appveyor.bat

* ruby: Use `RUBY_API_VER_LONG` instead of `RUBY_VER_LONG`
Stop using `RUBY_VER_LONG` because it is confusing.
* Set subsystem version properly
Subsystem version for Windows XP x64 should be 5.02, not 5.01.

Small fixes

---

README.md
appveyor.bat
appveyor.yml

* Update Racket to 6.10.1.
* Change Tcl DLL name from tcl86.dll to tcl86t.dll.
* Work around for the problem in #32. Copy the dll to the current directory and set $TCL_LIBRARY instead of adding $TCL_DIR/bin to the $PATH.

Update racket and fix tcl test

---

patch/0001-Disable-incsearch-highlight-test.patch

The test added by 8.0.1238 doesn't work well on Windows. Disable it temporarily.
It doesn't fail on vim/vim because winpty is not installed and the terminal feature doesn't work on it. Should be fixed later.

Disable a test for incsearch temporarily

---

appveyor.bat

ActivePerl 5.24.1 is not available anymore. Update to newer versions.
However ActiveState stops releasing 32-bit versions of ActivePerl.
Use the older version for x86.

Update ActivePerl to 5.24.2 and 5.24.3 (#60)

---

README.md
appveyor.bat
appveyor.yml

See #60.
Also update to Perl 5.28.
I confirmed that this worked fine on my AppVeyor account:
https://ci.appveyor.com/project/k-takata/vim-win32-installer/build/job/r1uw4ssemawr9y85
If we switch to Strawberry Perl, we should also update `if_perl.txt`:
https://github.com/vim/vim/blob/fda95e75721fb221495c69e493ec2761b5d85123/runtime/doc/if_perl.txt#L48
https://github.com/vim/vim/blob/fda95e75721fb221495c69e493ec2761b5d85123/runtime/doc/if_perl.txt#L284-L285
I will wait @brammool's opinion before merge this.

 Switch to Strawberry Perl from ActivePerl

---

appveyor.bat

No need to extract whole Ruby source to create config.h.
Extract only required files.
Also add some error checking and reduce some log messages.

Reduce time for creating Ruby's config.h

---

appveyor.bat

Reduce the unpacking time by extracting only the "perl" folder.
Strawberry Perl has two main folders: "c" and "perl".
The "c" folder contains MinGW compiler which will be used when compiling
some kind of CPAN modules.  It is not needed for compiling Vim or
testing if_perl.

if_perl: Extract only the "perl" folder

---

appveyor.bat
appveyor.yml
patch/0029-nsis-dosinst-Support-creating-64-bit-installer.patch

Create also 64-bit MUI2 installer with minimal changes.
It still uses the suffix `w32` even for 64-bit.
Results in my local account:
https://github.com/k-takata/vim-win32-installer/releases/tag/v8.1.0454-64bit-installer3

mui2: Create 64-bit installer

---

appveyor.yml

Commit 09afb79fa63c925fbbfff tried to linkify the files in the description setting of the release page.
Unfortunately, I forgot to add the github.com server name to the link target, so those links are currently broken. So fix this by adding the servername to the URL variable.
Sorry, I did not notice earlier and had a busy week without having time to check the previous PR.

Fix URL variable

---

appveyor.yml

Add a badge for the number of downloads per release.
Example visible here:
https://github.com/chrisbra/vim-win32-installer/releases/tag/v8.1_cb6

Add badge for number of downloads per release

---

patch/0039-nsis-Support-removing-private-vimfiles-directory.patch
patch/0040-nsis-Update-German-translation-by-chrisbra.patch
patch/0041-Update-danish.nsi.patch

* Update a message to reflect the changes in 8.1.0534.
* Update the uninstaller to be able to remove $HOME/vimfiles directory.
* Fix inconsistency between the installer and the uninstaller.
Change "vimfiles directory" to "plugin directories".

mui2: Update messages, etc.

---

appveyor.yml

Simply call them 64-bit/32-bit installer, because this is what they are.
Also, slightly reorder them, first the 64/32 bit installers, then the
zip archives with the corresponding pdb archives.
fixes #112

Remove the Experimental and Recommended labels

---

appveyor.yml

I don't know if this will work, so let's test this. It should sign the *.exe binaries from appveyor. 
The integration has been done according to the documentation:
https://about.signpath.io/documentation/build-system-integration#appveyor

Sign binaries using Signpath.io

---

appveyor.bat
appveyor.yml
patch/01_patchlevel_nsis_installer.patch

This PR does the following:
1) Add the patchlevel to the product version of the installer, this needs a change in how the nsis installer script is created. In addition this needs a patch for the nsis installer itself, however this second change needs to be applied to the vim repository, so a patch file is created
2) Create a zipfile consisting the exe installer as well as the zip archive of the Vim release. This can then be uploaded to signpath to have all parts signed. However once this is merged, it needs a change in the signpath configuration.

Nsis update for signpath

---

appveyor.yml

Some small changes, that already add the sections for the signed files. When uploading the signed files, add a (`_signed`) suffix to the generated files, and un-comment the signed section to have those download links appear.
Also, comment out some parts of the appveyor control file, that are apparently not needed by Signpath.
While add it, remove an old comment, that is obviously wrong now.

Updated signing

---

appveyor.bat

Fixes #134.
We should wait the next release of gettext-iconv-windows.

Downgrade to gettext 0.19.8.1 + iconv 1.15

---

scripts/update-repo.sh

E.g. https://github.com/vim/vim-win32-installer/releases/tag/v8.1.2397
`__QNXNTO__` is shown as __QNXNTO__, which is unintended.
`_` and some other characters need to be escaped.

Escape some characters for markdown

---

README.md
appveyor.yml

some updates to the description. 
First of all, recommend more prominently, to use the 32bit installer, 
While updating the description, I noticed, that the link to the wiki still points to wikia.com, while it seems to be now fandom.com, so update that as well.
And finally, reorder the download artifacts a bit. Since we recommend to use the 32bit installer, always put the 32bit artifact first, followed by the corresponding 64bit artifact.

Description

---

appveyor.yml

Collapse some informations from the release page. 
Looks like this: https://github.com/chrisbra/vim-win32-installer/releases/tag/v8.2.0083.cb6

collapse some parts of the release notes

---

appveyor.bat

https://github.com/mlocati/gettext-iconv-windows/releases/tag/v0.20.2-v1.16
Now libgcc_s_sjlj-1.dll is not needed.

Update gettext-iconv-windows to v0.20.2-v1.16

---

appveyor.yml

When someone clicked a downloads image, the image itself was opened.
It was not so useful. This PR changes the link target to each file.

Fix link target of downloads images

---

.github/workflows/update-release-list.yaml
scripts/update-release-list.py

When a release is newly created, a workflow will run on GitHub Actions.
It fetches this repository and the wiki repository, then gets the
information about latest releases via GitHub API, then updates the
Releases List, then pushes to the wiki page.

Update the Releases List automatically

---

README.md
appveyor.bat
appveyor.yml

This reverts commit d09bcac8b48f43f011abf729ffe0badbe699042b.
The TCL URL does not work currently. In addition, it needs some quoting, so the build currently fails. Let's disable it again until this issue has been resolved with ActiveState.

Revert "Temporarily enable TCL for 64bits"

---

scripts/update-repo.sh

Start generating the changelog from the latest release from github,
instead of the latest known git submodule tag. This matters, if a
previous release failed to upload, we want to have included the previous
changes as well.
this is not tested yet.

Get release logs from latest github release

---

README.md
appveyor.bat
appveyor.yml

This will use the TCL 8.6.6 binaries provided by ActivateState
but currently only 32bit builds are available.
Now waiting for 64bit builds to be used for our projects.

Enable TCL again

---

appveyor.bat

https://github.com/mlocati/gettext-iconv-windows/releases/tag/v0.21-v1.16
libgcc_s_sjlj-1.dll was not needed, but it was still included in the
installer. Avoid including it by deleting it before creating the
installer.

Update gettext-iconv-windows to v0.21-v1.16

---

README.md
appveyor.bat
appveyor.yml

Unfortunately, the appveyor build images for Visual Studio 2015 do not include Python3.9, so we have to install it ourselves. 
Therefore  download python3.9 manually and install it below `c:\python39`.
Alternatively, we could switch to Visual Studio 2019, but not sure if this would be okay.
This closes https://github.com/vim/vim-win32-installer/issues/203

Switch to Python3.9

---

README.md
appveyor.bat
appveyor.yml

Enable and distribute libsodium together with vim. 
Currently blocked by https://github.com/vim/vim/pull/8428

Enable Sodium feature

---

README.md
appveyor.bat
appveyor.yml

* Add (BC) to the documents.
Now Racket provides two variants: BC and CS.
The CS version provides new APIs, but they are not compatible with our
code. We should use the BC version.
* Use the tgz package instead of the installer.
PLTCOLLECTS and PLTCONFIGDIR need to be set manually.

Update Racket to 8.3 (BC)

---

appveyor.bat

This will be fixed by changing the link option `/LTCG:STATUS` to `/LTCG` in https://github.com/vim/vim/pull/9631.

Remove workaround for suppressing the progress of link

---

appveyor.yml

The content of Interface Information part have been recognized as HTML, not Markdown.

Fix formatting issue in release notes

---

appveyor.bat
appveyor.yml

Create a release as a draft, and if the x86 build is finished successfully, turn off the draft status.
This is a workaround for #262.

CI: Don't publish an incomplete release

---

scripts/update-release-list.py

Close #267
It seems that 'published_at' is not always available. Fall back to 'created_at'.

Use 'created_at' if 'published_at' is not available

---

appveyor.bat
scripts/patchlevel.sh

This uses a different approach to get the correct patchlevel. Instead of
extracting the patch from version.c, it uses the tag name for that. This
matters for Patches like 9.0.0049, which previously used the patchlevel
of 49 but it should be '0049'
This patchlevel will be used as DisplayVersion and stored in the Windows
registry. winget makes use of the DisplayVersion field and compares that
against the version in its repository (which will again use the tag
version) to decide whether an update of the package should be done.
But instead of relying on the VIM_TOSTR macros, quote the patchlevel
correctly and replace the VIM_VERSION_PATCHLEVEL_STR macro directly with
the actual (quoted) patchlevel.
So this makes sure we use the proper version string for the installed
Windows Vim installer …

Extract Patchlevel correctly from the Appveyor tag into Vims version.h

---

scripts/patchlevel.sh

As mentioned in #284, the change db248dd that directly set the VIM_VERSION_PATCHLEVEL_STR did not modify the VIM_VERSION_PATCHLEVEL macro, which causes another breakge.
So in addition, also set the VIM_VERSION_PATCHLEVEL macro to the decimal number (removing leading zeroes).
fixes #284

Also set the VIM_VERSION_PATCHLEVEL macro to the decimal patchlevel

---

.github/workflows/update-release-list.yaml
scripts/update-release-list.py

* Set permissions of CI.
* Update dependencies.
* Revise update-release-list.py.

Adjust update-release-list

---

appveyor.bat

Might be flagged as suspicious by AV vendors because of the use of UPX
I don't know if this is a good idea, but I'd like to see how much space this causes. So let's check it.

Disable UPX to prevent Anti-Virus flagging

---

.github/workflows/winget_nightly.yml
.github/workflows/winget_stable.yml

Winget Releaser now supports non-Windows runners, and `ubuntu-latest` is generally faster.

Change Winget Releaser job to `ubuntu-latest`

---

appveyor.yml

Currently, CI is executed twice every day:
* When the master branch is updated.
* When a tag is pushed.
We don't need to run CI when the master branch is updated. Skip it.
Note: If a user created a PR to the master branch, %APPVEYOR_REPO_BRANCH% will be set to "master". To skip only the master branch, we need to check that %APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH% is undefined.

CI: Skip master branch

---

appveyor.yml

The tag build was skipped unintentionally in #343.
Check %APPVEYOR_REPO_TAG%.

CI: Fix tag build

---

appveyor.bat

Accept "-" and "+" as delimiters so that we can use semver style tags (mainly for CI debugging).  See: https://semver.org/
Now, pre-release version and/or build metadata can be added. E.g.: `v9.1.0123-1`, `v9.1.0123+debug`

CI: Accept semver style tags

---

scripts/update-repo.sh

If the previous release's last commit was not a tagged commit (e.g. runtime file update), the last commit was also listed in the bottom of the new changelog.
Check the changelog of the previous release and extract the latest commit id to avoid the duplication.

CI: Remove duplicated items from changelog

---

appveyor.yml

Don't call `appveyor exit` at very beginning.
It caused errors on `on_success` and `on_failure`.
https://ci.appveyor.com/project/k-takata/vim-win32-installer/builds/50273455/job/a5790xthkui300uv
```
"%APPVEYOR_BUILD_FOLDER%\appveyor.bat" onsuccess
'"C:\projects\vim-win32-installer\appveyor.bat"' is not recognized as an internal or external command,
operable program or batch file.
Command exited with code 1
"%APPVEYOR_BUILD_FOLDER%\appveyor.bat" onfailure
'"C:\projects\vim-win32-installer\appveyor.bat"' is not recognized as an internal or external command,
operable program or batch file.
Command exited with code 1
```

CI: Partially revert #349

---

README.md

* The maxAge parameter seems to be deprecated.  Remove it.
* Show the latest release name instead of the latest tag. Also, change the link to the latest release.

doc: Update badges

---

appveyor.bat

To support Windows 7 again.
https://github.com/mlocati/gettext-iconv-windows/releases/tag/v0.22.5a-v1.17-r3

Update gettext-iconv-windows to v0.22.5a-v1.17-r3
