vim/vim-win32-installer

scripts/update-repo.sh

Should also catch things like beta release numbers (adding alpha chars to the release number)

tigthen regex a little bit

---

appveyor.bat
if_ver.vim

Fix hang with the latest Vim patches

Fix hanging in Appveyor

---

README.md
appveyor.bat
appveyor.yml

Update Racket to 6.6

---

README.md

Fixed python2 typo

---

appveyor.bat

* Setting for targeting WinXP didn't actually work.
* Fix PATH for Ruby 2.4.1.
* Update UPX to 3.94.

Fix compiler options, etc.

---

appveyor.bat

The directory structure was changed to install both 32- and 64-bit
gvimext.dll and corresponding iconv and gettext dlls.

Update appveyor.bat for 8.0.1191

---

scripts/update-repo.sh

Amend the sed call and double all backslashes. This fixes #66
Thanks @k-takata for noticing

Backslashes need to be escaped

---

patch/0026-nsis-Adjust-wording.patch
patch/0027-nsis-Make-the-1st-section-read-only.patch
patch/0028-nsis-Make-uninstalling-more-precise.patch

* Adjust wording.
* Make the 1st section of the uninstaller read only.
* Make the uninstaller more precise.

mui2: Add some more patches

---

appveyor.yml

updated appveyor.yml and include links to the file description names.
Should look similar to this result here:
https://github.com/chrisbra/vim-win32-installer/releases/tag/v8.1_cb4

make links of the file description names

---

patch/0030-nsis-Improve-some-messages.patch

Show a message while waiting the uninstall of old version, or while
executing install.exe or uninstal.exe.

mui2: Improve some messages

---

patch/0031-nsis-Update-Filelist.patch
patch/0032-nsis-Work-around-NSIS-Japanese-translation.patch
patch/0033-dosinst-Remove-needless-sleeps.patch

* Update Filelist. (This is not important for NSIS, though.)
* Work around Japanese translation.
* Reduce needless sleeps for faster installation.

mui2: Add more improvements

---

patch/0035-nsis-No-need-to-use-DetailUpdate.patch

`DetailPrint` is enough for our usage.

mui2: No need to use ${DetailUpdate}

---

patch/0008-dosinst-Adjust-the-default-_vimrc.patch
patch/0009-nsis-Use-nsExec-Exec-instead-of-ExecWait.patch
patch/0010-nsis-Use-MUI2.patch
patch/0011-nsis-Use-InstallLib-for-installing-DLLs.patch
patch/0012-nsis-Support-translation.patch
patch/0013-nsis-Add-workarounds-for-Japanese-NSIS-messages.patch
patch/0014-nsis-Fix-some-ifdef-conditions.patch
patch/0015-nsis-Fix-installer-directory.patch
patch/0016-nsis-Remove-old-codes.patch
patch/0017-dosinst-Support-setting-Vi-compatibility-from-comman.patch
patch/0018-nsis-Add-uninstallation-check.patch
patch/0019-nsis-Support-setting-Vi-compatibility.patch
patch/0020-nsis-Use-DropLists-instead-of-RadioButtons.patch
patch/0021-nsis-Add-vim_-prefix-to-registry-values.patch
patch/0022-nsis-Make-uninstalling-more-precise.patch
patch/0023-nsis-dosinst-Support-creating-64-bit-installer.patch
patch/0024-nsis-Improve-some-messages.patch
patch/0025-nsis-Update-Filelist.patch
patch/0026-dosinst-Remove-needless-sleeps.patch
patch/0027-dosinst-Add-some-comments-to-the-default-_vimrc.patch
patch/0028-nsis-Translate-some-messages.patch

See: https://github.com/vim/vim/pull/3525#issuecomment-429213510

mui2: Revise dosinst patches

---

patch/0031-nsis-Comment-out-unused-translation-messages.patch

They were needed for gpwen's version. Currently, they are not used.

mui2: Comment out unused translation messages

---

patch/0029-Update-German-translations.patch
patch/0030-nsis-Adjust-some-messages-and-adjust-layout-for-them.patch
patch/0031-nsis-Add-the-language-selection-dialog.patch
patch/0032-nsis-Move-some-functions-after-the-sections.patch
patch/0033-nsis-Remember-the-user-s-custom-selections.patch

* Update German translations.
* Adjust some English messages and adjust the layout.
* Add the language selection dialog.
* Remember the user's custom selections.

mui2: Update German translations, etc.

---

patch/0034-Update-danish.nsi.patch
patch/0035-nsis-dosinst-Make-uninstaller-silent-when-installing.patch
patch/0036-nsis-Update-German-translation.patch
patch/0037-Update-danish.nsi.patch

Also update Danish and German translations.

mui2: Make uninstaller silent when installing

---

patch/0038-nsis-Don-t-show-any-message-boxes-in-the-silent-mode.patch

Fix usage of /SD in MessageBox.

mui2: Fix PR #98

---

appveyor.bat

Unpack nsis/icons.zip

---

appveyor.bat

Show the build log of GvimExt for debugging.
(I also need to update the URL of Racket. The old URL doesn't respond now.)

Show build log of GvimExt and set CPU explicitly

---

appveyor.yml

Change signing policy to release as per comment in https://github.com/vim/vim/issues/1142#issuecomment-489535671

Change signing policy to release

---

patch/01_nsis_progname.patch

Add patch to add Versioninfo to installer

---

patch/01_nsis_progname.patch

https://github.com/vim/vim/issues/1142#issuecomment-492454699

Updated nsis versionname patch

---

appveyor.bat

Adjust the sed workaround for 8.1.1697

---

appveyor.bat

Rename uninstal.exe to uninstall.exe.

Update for 8.1.2082

---

appveyor.bat

Add patchlevel to file version metadata

---

appveyor.bat

Add a comment about CHERE_INVOKING

---

README.md

Linking to the top page is not so useful.

README: Change a link to the releases page

---

scripts/update-repo.sh

* Add link to each commit instead of each tag.
(I don't think that link to each tag is so useful.)
This also adds a link to runtime files update.
* Simplify the sed expressions. Bram has changed the style of commit log
a few years ago. No need to drop 'Problem:' or limit to 100 characters anymore.
* Use separate commands for creating changelog for markdown and plain text.

Revise changelog

---

README.md
appveyor.yml

mention, that a new certificate has been created.

Mention newly created certificate

---

appveyor.bat

Downloading may sometimes fail. Retry once.

Retry downloading if failed

---

README.md
appveyor.bat
appveyor.yml

See #194.
It looks like public downloads of ActiveTcl are no longer possible.

Disable Tcl temporarily

---

README.md
appveyor.bat
appveyor.yml

Test TCL for 64bits
this is a temporary fix

Tcl url test

---

README.md
appveyor.bat
appveyor.yml
scripts/winget.vim
scripts/winget_template.yml

This PR contains actually two different changes. (I should probably split those up into 2 PRs).
- Make whitespace indentation in appveyor.bat consistent and always use `Tab` for indentation
- Create a sample winget yaml file. This could be used for `https://github.com/microsoft/winget-pkgs/` to provide easier new versions for the new winget package manager.
It looks like `winget` is becoming the new package manager to install packages on Windows 10, so I thought it might make sense to provide a sample winget.yml file, that could then be used to upload it to `https://github.com/microsoft/winget-pkgs/` and provide new versions. Currently, it does not seem to be possible to automatically submit new versions directly, see e.g. https://github.com/microsoft/winget-pkgs/issues/2399
However, I am …

Create Winget Yaml File

---

appveyor.bat

nsis: Install ShellExecAsUser

---

appveyor.yml

Okay, so github wants me to regenerate the auth token. So here we go

Regenerate Github Personal Access Token

---

README.md
appveyor.bat
appveyor.yml

ActiveTcl 8.6.6 is not available anymore. Disable it for now.
Close #242
Close #244

Disable ActiveTcl 8.6.6

---

appveyor.bat
appveyor.yml

Don't leave the draft release on failure of the x86 build.

CI: Delete the draft release on failure

---

appveyor.yml

doc: add message if release contains signed artifacts

---

appveyor.bat

Windows makefiles were renamed in 9.0.0421.
Change the code to support it.

Update for 9.0.0421

---

appveyor.bat
appveyor.yml

Make it possible to run builds on a PR.
Deploy only on tags.

Run builds on normal commits

---

README.md
appveyor.bat
appveyor.yml

Close #290 
I would appreciate it if you could merge this PR if you deem it appropriate.

Update interface for Python 3 (3.10 to 3.11)

---

.github/dependabot.yml
.github/workflows/winget.yml

- v2 fixes https://github.com/vedantmgoyal2009/winget-releaser/issues/86
Also, add Dependabot to automatically bump GitHub action dependencies.

Bump vedantmgoyal2009/winget-releaser to v2 & Add dependabot

---

README.md

Hi!
I am the developer evangelist of SignPath.
I hope it is ok that I created a PR without issue first.
It is only a slight update of the mention of SignPath with some UTM links.
We get a lot of traffic from GitHub and would like to understand who is interested in a code-signing solution.

Update mention of SignPath

---

README.md
appveyor.bat
appveyor.yml

Switch to Ruby 3.2

---

.github/workflows/winget_nightly.yml
.github/workflows/winget_stable.yml
README.md
scripts/do_next_stable_release.sh
scripts/get_last_windows_release.sh

winget: use vim.vim.nightly identifier

---

appveyor.bat

exclude syntax testdir directory

---

README.md
appveyor.bat
appveyor.yml

However, it seems MSVC v140 is no longer available, not sure if this will cause problems...

Update libsodium to 1.0.19

---

appveyor.bat

The removal of the UPX definition is commented out

The removal of the UPX definition is commented out

---

appveyor.bat

* Use better compression level for distributed files.
* Use faster compression level for intermediate files.

package: Adjust compression level

---

.github/workflows/update-repo.yml
appveyor.yml

* Call `appveyor exit` at very beginning.
* Fold long line.
* Remove unnecessary `call`.
* Don't run update-repo on forked repositories.

CI: Revise some minor items

---

appveyor.bat

Enable VIMDLL to reduce the package size.

package: Enable VIMDLL

---

appveyor.bat

CI: Specify --depth on submodule update

---

appveyor.bat

https://github.com/mlocati/gettext-iconv-windows/releases/tag/v0.22.5a-v1.17

Update gettext-iconv-windows to v0.22.5a-v1.17

---

appveyor.bat

https://github.com/mlocati/gettext-iconv-windows/releases/tag/v0.22.5a-v1.17-r2

Update gettext-iconv-windows to v0.22.5a-v1.17-r2

---

appveyor.bat

Changes in the installer build for MS Windows.
Dependency on https://github.com/vim/vim/pull/16378

changes in nsis

---

.github/workflows/windows-arm-build.yml
README.md
appveyor.bat

Refactor and build Windows Arm64 versions

---

appveyor.bat

slight refactoring of the `appveyor.bat` file

slight refactoring of the `appveyor.bat` file

---

appveyor.bat

closes #381 
Related [PR vim#17642](https://github.com/vim/vim/pull/17642)

Building the installer for ARM64
